[supervisord]
nodaemon=true
user=root

[program:frontend]
# Executes dotnet run in Release mode specifically
command=dotnet run --project frontend.csproj --configuration Release 
directory=/app/frontend/frontend
autostart=true
autorestart=true
stderr_logfile=/var/log/frontend.err.log
stdout_logfile=/var/log/frontend.out.log
# Ensure the environment is set to Production/Release
environment=ASPNETCORE_ENVIRONMENT="Production"
