services:
  blackhat-fe:
    image: blackhatbadshah.azurecr.io/vermasj/blackhatbadshahfe
    ports:
      - "7001:8080"
    restart: always

  blackhat-ai:
    image: blackhatbadshah.azurecr.io/vermasj/blackhatbadshahai
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TOGETHER_API_KEY=${TOGETHER_API_KEY}
    ports:
      - "8501:8000"
    restart: always

  blackhat-be:
    image: blackhatbadshah.azurecr.io/vermasj/blackhatbadshahbe
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION:-ap-south-1}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-ap-south-1}
      - ConnectionStrings__DefaultConnection=${ConnectionStrings__DefaultConnection}
      - Razorpay__KeyId=${RAZORPAY_KEY_ID}
      - Razorpay__KeySecret=${RAZORPAY_KEY_SECRET}
      - Razorpay__WebhookSecret=${RAZORPAY_WEBHOOK_SECRET}
      - Keycloak__AdminClientSecret=${KEYCLOAK_ADMIN_CLIENT_SECRET}
    volumes:
      - ./log-storage:/mnt/log-storage
    ports:
      - "5092:8080"
    restart: always
